<?php

namespace AppBundle\Repository;

/**
 * VpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VpsRepository extends \Doctrine\ORM\EntityRepository
{
}
